### ISSUE TITLE
severe FPS drop when the boss's tower collapse.

### ISSUE THREAD

**Issue by zenAndroid** [simshadows/basictd#1]
This issue **stops** me from advancing in the levels.

*sorry*

u can delet this afterwards, it's going to embarass you someday

**Comment by zenAndroid** [comment]
Turns out you can't delete an issue from github ... sorry dawg ... i guess you're gonna have to start a new repo and delete this one, RIP you tower defense game.

**Comment by simshadows** [comment]
rip
